### PR TITLE
updated pianoman supporting newer versions

### PR DESCRIPTION
**Pull request by boaz0**
there were many changes at `rdb-check-dump.c` in `redis` project and i have tried to close these gaps, by supporting rdb files newer than version 2.

### CODE REVIEW

**Comment by mrb** [comment]
@ripcurld00d Wow! This is awesome work, thanks. Will take some time to review. It would be cool to collect various "fixture" .rdb files from various versions and make some tests to assert that the various formats work. Did you verify that this patch maintains correct behavior for older .rdb files as well? Thanks again.

**Comment by boaz0** [comment]
unfortunately, i don't have old ones. i have just run it on the rdb files that `redis-rdb-tools` is using for its tests, though. i do agree that we should add tests to `pianoman` and include older versions of rdb files. 
if you give me couple of weeks, i think i can organize old version rdbs, and maybe start working on a test script.
:)

**Comment by mrb** [comment]
@ripcurld00d I might have some older files around. One thing that would be really helpful is if we could come up with a script that would fill a redis db with the right mix of strings, hashes, etc so that we could know that all parts of pianoman were being exercised.

**Comment by boaz0** [comment]
@mrb I am not sure if it is possible. however, it does sound very challenging and interesting. I guess a deeper look at the rdb.c (https://github.com/antirez/redis/blob/unstable/src/rdb.c) code may help us

**Comment by mrb** [comment]
@ripcurld00d if you have some time, poke around here https://github.com/antirez/redis/tree/unstable/tests

**Comment by boaz0** [comment]
Hi @mrb. I am sorry for not posting for a long-long time...
Anyway, I have seen the unit-tests and assuming the RDB part is what we need, it requires overhead of code files from Redis, in order to use it in `piano-man`. Another idea is writing a code that creates RDB files and then tests that check for correlation between `piano-man` output to what has been expected to be the result.
So I guess it's up to you...

Unless, I have misunderstood.

**Pull request closed without merging**
